### Dar de alta alumno
POST http://localhost:4004/odata/v2/academic/Alumnos
Content-Type: application/json

{
    "dni": "41531236",
    "nombre": "Federico",
    "apellido": "Gavaz",
    "email": "federicogavaz@juanXXIII.com"
}

### Probar Action Ping
POST http://localhost:4004/odata/v2/academic/ping
Content-Type: application/json
